spring:
  datasource:
    url: jdbc:mysql://localhost/wiki_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: choerodon
    password: choerodon
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          zkNodes: 127.0.0.1:2181
      default-binder: kafka
    bus:
      enabled: true
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0
    stream:
      enabled: true
choerodon:
  saga:
    consumer:
      thread-num: 5 # saga消息消费线程池大小
      max-poll-size: 200 # 每次拉取消息最大数量
      enabled: true # 启动消费端
      poll-interval-ms: 1000 # 拉取间隔，默认1000毫秒
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true
wiki:
  client: xwiki
  url: http://xwiki.staging.saas.hand-china.com
  token: Choerodon
  default-group: XWikiAllGroup
  sync: false #是否服务启动之后自动同步组织和项目
#feign:
#  hystrix:
#    shareSecurityContext: true
#    command:
#      default:
#        execution:
#          isolation:
#            thread:
#              timeoutInMilliseconds: 10000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8000/eureka/}
    registryFetchIntervalSeconds: 10


