#spring:
#  sleuth:
#    integration:
#      enabled: false
#    scheduled:
#      enabled: false
#    sampler:
#      percentage: 1.0
#    stream:
#      enabled: true
#  datasource:
#    url: jdbc:mysql://localhost/demo_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
#  kafka: #使用原生spring kafka需要配置
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: demo-service
#      auto-offset-reset: earliest
#  cloud:
#    bus:
#      enabled: true
#    stream:
#      kafka:
#        binder:
#          brokers: 127.0.0.1:9092
#          zkNodes: 127.0.0.1:2181
#
#mybatis:
#  mapperLocations: classpath*:/com.test.devops.mapper/*.xml
#  configuration: # 数据库下划线转驼峰配置
#    mapUnderscoreToCamelCase: true
#eureka:
#  instance:
#    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 10
#    leaseExpirationDurationInSeconds: 30
#    metadata-map:
#      VERSION: v1
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8000/eureka/}
#    registryFetchIntervalSeconds: 10
#
